id: P002910
initial_creation_type: ocr
source_metadata:
  id: bdr:W21914
  title: སྤྱོད་འཇུག་རྩ་འགྲེལ
  author: ''
  volumes:
    f69352ed430b49d8be007f748d81d225:
      image_group_id: I5058
      title: ''
      volume_number: 1
      total_pages: 466
      base_file: v001.txt
